name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Adjust if your default branch has a different name
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'  # Set this to the node version you are using locally

      - name: Build and Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEBAPPS_API_TOKEN_INSPECTIONS_REACT_APP }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Provides Azure Static Web Apps access to your repo
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          app_location: "/"  # Assumes your app is in the root of your repo
          api_location: ""  # Set this if you have an API; otherwise leave blank
          output_location: "build"  # The location of your build output directory

      - name: Cleanup
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
